[package]
name = "rocm_smi_lib"
version = "0.1.0-beta"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.147"

[build-dependencies]
cmake = "0.1.31"
