[package]
name = "rocm_smi_lib"
version = "0.1.6-beta"
edition = "2021"
license = "GPL-3.0"
authors = ["WhiskyAKM"]
description = "easy to use crate for using rocm-smi from rust"
repository = "https://github.com/PTFOPlayer/rocm_lib"
categories = ["api-bindings", "external-ffi-bindings", "hardware-support"]
keywords = ["radeon", "rsmi", "hip", "rocm", "gpu"]

[dependencies]
libc = "0.2.147"

[build-dependencies]
cmake = "0.1.31"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3