[package]
name = "rocm_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi = "0.0.2"
libc = "0.2.147"


[build-dependencies]
cmake = "0.1.31"
